# paths to files
[cirrus-hl]

[cirrus-hl.jr_local]
base_dir = "E:/CIRRUS-HL/01_Flights"
raw = "SMART/raw"  # raw measurements as given by SMART
data = "SMART/data_cor"  # dark current corrected data
calibrated = "SMART/data_calibrated"  # calibrated and dark current corrected data
quicklooks = "quicklooks"  # quicklook path
horidata = "horidata"  # INS and stabilization data
bahamas = "BAHAMAS"  # BAHAMAS measurement files
bacardi = "BACARDI"  # BACARDI measurement files
libradtran = "libRadtran"  # LibRadTran simulation files
all = "all"  # all measurements from one instrument in on instrument folder
plot = "C:/Users/Johannes/Documents/campaigns/CIRRUS-HL/SMART/plots"  # standard plot path
calib = "C:/Users/Johannes/Documents/campaigns/CIRRUS-HL/03_Calibration"  # calibration measurements
pixel_wl = "C:/Users/Johannes/Documents/Doktor/instruments/SMART/pixel_wl"  # pixel to wavelength mapping files
lamp = "C:/Users/Johannes/Documents/Doktor/instruments/SMART/lamp_F1587"  # lamp specification files
panel = "C:/Users/Johannes/Documents/Doktor/instruments/SMART/panel_34816"  # panel reflectivity files
gopro = "C:/Users/Johannes/Documents/Gopro"  # directory of GoPro time lapse pictures

[cirrus-hl.jr_ubuntu]
base_dir = "/mnt/e/CIRRUS-HL/01_Flights"
raw = "SMART/raw"  # raw measurements as given by SMART
data = "SMART/data_cor"  # dark current corrected data
calibrated = "SMART/data_calibrated"  # calibrated and dark current corrected data
quicklooks = "quicklooks"  # quicklook path
horidata = "horidata"  # INS and stabilization data
bahamas = "BAHAMAS"  # BAHAMAS measurement files
plot = "/mnt/c/Users/Johannes/Documents/campaigns/CIRRUS-HL/SMART/plots"  # standard plot path
calib = "/mnt/c/Users/Johannes/Documents/campaigns/CIRRUS-HL/03_Calibration"  # calibration measurements
pixel_wl = "/mnt/c/Users/Johannes/Documents/Doktor/instruments/SMART/pixel_wl"  # pixel to wavelength mapping files
lamp = "/mnt/c/Users/Johannes/Documents/Doktor/instruments/SMART/lamp_F1587"  # lamp specification files
panel = "/mnt/c/Users/Johannes/Documents/Doktor/instruments/SMART/panel_34816"  # panel reflectivity files
gopro = "/mnt/c/Users/Johannes/Documents/Gopro"  # directory of GoPro time lapse pictures

# on LIM server
[cirrus-hl.lim_server]
base_dir = "/projekt_agmwend/data/Cirrus_HL/01_Flights"
raw = "SMART/raw"  # raw measurements as given by SMART
data = "SMART/data_cor"  # dark current corrected data
calibrated = "SMART/data_calibrated"  # calibrated and dark current corrected data
quicklooks = "quicklooks"
horidata = "horidata"  # path to INS and stabilization data
bahamas = "BAHAMAS"  # path to BAHAMAS measurement files
bacardi = "BACARDI"  # BACARDI measurement files
calib = "/projekt_agmwend/data/Cirrus_HL/03_Calibration"  # calibration measurements
pixel_wl = "/projekt_agmwend/kalibration/Spektros/pixel_wl"  # pixel to wavelength mapping files
lamp = "/projekt_agmwend/kalibration/Lamps/FEL-1587"  # lamp specification files
panel = "/projekt_agmwend/kalibration/Panels/34816"  # panel reflectivity files
gopro = "/projekt_agmwend/data/Cirrus_HL/04_Gopro"  # directory of GoPro timestamps files
