[cirrus-hl]

[cirrus-hl.jr_local]
base_dir = "E:/CIRRUS-HL/01_Flights"
raw = "SMART/raw"  # raw measurements as given by SMART
data = "SMART/data_cor"  # dark current corrected data
calibrated = "SMART/data_calibrated"  # calibrated and dark current corrected data
quicklooks = "quicklooks"  # quicklook path
horidata = "horidata"  # INS and stabilization data
bahamas = "BAHAMAS"  # BAHAMAS measurement files
bacardi = "BACARDI"  # BACARDI measurement files
wales = "WALES"  # Lidar measurement files
libradtran = "libRadtran"  # LibRadTran simulation files
satellite = "satellite"  # satellite images
all = "all"  # all measurements from one instrument in one instrument folder
calib = "E:/CIRRUS-HL/03_Calibration"  # calibration measurements
gopro = "E:/CIRRUS-HL/04_Gopro"  # directory of GoPro time lapse pictures
ifs_raw = "E:/Cirrus_HL_raw_only/05_IFS_ecmwf"
ifs = "E:/CIRRUS-HL/05_IFS_ecmwf"
ozone = "E:/Cirrus_HL_raw_only/06_ozone_sondes"
ecrad = "E:/CIRRUS-HL/07_ecrad"
plot = "C:/Users/Johannes/Documents/Doktor/campaigns/CIRRUS-HL/case_studies"  # standard plot path
pixel_wl = "C:/Users/Johannes/Documents/Doktor/instruments/SMART/pixel_wl"  # pixel to wavelength mapping files
cosine = "C:/Users/Johannes/Documents/Doktor/instruments/SMART/cosine_correction_factors"  # cosine correction factors
lamp = "C:/Users/Johannes/Documents/Doktor/instruments/SMART/lamp_F1587"  # lamp specification files
panel = "C:/Users/Johannes/Documents/Doktor/instruments/SMART/panel_34816"  # panel reflectivity files

[cirrus-hl.jr_ubuntu]
base_dir = "/mnt/e/CIRRUS-HL/01_Flights"
raw = "SMART/raw"  # raw measurements as given by SMART
data = "SMART/data_cor"  # dark current corrected data
calibrated = "SMART/data_calibrated"  # calibrated and dark current corrected data
quicklooks = "quicklooks"  # quicklook path
horidata = "horidata"  # INS and stabilization data
bahamas = "BAHAMAS"  # BAHAMAS measurement files
bacardi = "BACARDI"  # BACARDI measurement files
wales = "WALES"  # Lidar measurement files
libradtran = "libRadtran"  # LibRadTran simulation files
satellite = "satellite"  # satellite images
plot = "/mnt/c/Users/Johannes/Documents/campaigns/CIRRUS-HL/case_studies"  # standard plot path
calib = "/mnt/c/Users/Johannes/Documents/campaigns/CIRRUS-HL/03_Calibration"  # calibration measurements
pixel_wl = "/mnt/c/Users/Johannes/Documents/Doktor/instruments/SMART/pixel_wl"  # pixel to wavelength mapping files
cosine = "/mnt/c/Users/Johannes/Documents/Doktor/instruments/SMART/cosine_correction_factors"  # cosine correction factors
lamp = "/mnt/c/Users/Johannes/Documents/Doktor/instruments/SMART/lamp_F1587"  # lamp specification files
panel = "/mnt/c/Users/Johannes/Documents/Doktor/instruments/SMART/panel_34816"  # panel reflectivity files
gopro = "/mnt/e/CIRRUS-HL/04_Gopro"  # directory of GoPro time lapse pictures

# on LIM server
[cirrus-hl.lim_server]
base_dir = "/projekt_agmwend/data/Cirrus_HL/01_Flights"
raw = "SMART/raw"  # raw measurements as given by SMART
data = "SMART/data_cor"  # dark current corrected data
calibrated = "SMART/data_calibrated"  # calibrated and dark current corrected data
quicklooks = "quicklooks"
horidata = "horidata"  # path to INS and stabilization data
bahamas = "BAHAMAS"  # path to BAHAMAS measurement files
bacardi = "BACARDI"  # BACARDI measurement files
wales = "WALES"  # Lidar measurement files
libradtran = "libRadtran"  # LibRadtran simulation files
satellite = "satellite"  # satellite images
all = "all"  # all measurements from one instrument in one instrument folder
calib = "/projekt_agmwend/data/Cirrus_HL/03_Calibration"  # calibration measurements
gopro = "/projekt_agmwend/data/Cirrus_HL/04_Gopro"  # directory of GoPro timestamps files
ifs = "/projekt_agmwend/data/Cirrus_HL/05_IFS_ecmwf"
ifs_raw = "/projekt_agmwend2/data_raw/Cirrus_HL_raw_only/05_IFS_ecmwf"
ecrad = "/projekt_agmwend/data/Cirrus_HL/07_ecrad"
ozone = "/projekt_agmwend2/data_raw/Cirrus_HL_raw_only/06_ozone_sondes"  # ozone sondes
plot = "/projekt_agmwend/home_rad/jroettenbacher/case_studies"  # general folder for plots
pixel_wl = "/projekt_agmwend/kalibration/Spektros/pixel_wl"  # pixel to wavelength mapping files
lamp = "/projekt_agmwend/kalibration/Lamps/FEL-1587"  # lamp specification files
panel = "/projekt_agmwend/kalibration/Panels/34816"  # panel reflectivity files
cosine = "/projekt_agmwend/kalibration/Cosinuskorrekturfaktoren/HALO_Einlässe"  # cosine correction factors

[halo-ac3]

[halo-ac3.jr_local]
base_dir = "E:/HALO-AC3/02_Flights"
raw = "SMART/raw"  # raw measurements as given by SMART
data = "SMART/data_cor"  # dark current corrected data
calibrated = "SMART/data_calibrated"  # calibrated and dark current corrected data
P5_smart = "SMART/idl_sav_files"
quicklooks = "quicklooks"  # quicklook path
horidata = "horidata"  # INS and stabilization data
bahamas = "BAHAMAS"  # BAHAMAS measurement files
bacardi = "BACARDI"  # BACARDI measurement files
libradtran = "libRadtran"  # LibRadTran simulation files
satellite = "satellite"  # satellite images
dropsondes = "dropsondes/Level_1"  # dropsonde quality controlled nc files
kt19 = "KT19"
hamp_mira = "hamp_mira"  # radar data from mira
wales = "WALES"  # lidar data from WALES
varcloud = "varcloud_retrieval"  # varcloud retrieval from LMU using WALES and HAMP
all = "all"  # all measurements from one instrument in on instrument folder
plot = "C:/Users/Johannes/Documents/Doktor/campaigns/HALO-AC3/case_studies"  # standard plot path
calib = "E:/HALO-AC3/03_Calibration"  # calibration measurements
pixel_wl = "C:/Users/Johannes/Documents/Doktor/instruments/SMART/pixel_wl"  # pixel to wavelength mapping files
lamp = "C:/Users/Johannes/Documents/Doktor/instruments/SMART/lamp_F1587"  # lamp specification files
cosine = "C:/Users/Johannes/Documents/Doktor/instruments/SMART/cosine_correction_factors"  # cosine correction factors
gopro = "E:/HALO-AC3/04_Gopro"  # directory of GoPro time lapse pictures
ifs_raw = "E:/HALO-AC3_raw_only/09_IFS_ECMWF"  # raw IFS data as downloaded
ifs = "E:/HALO-AC3/09_IFS_ECMWF"  # IFS data after first processing
cams_raw = "E:/HALO-AC3_raw_only/11_CAMS"
cams = "E:/HALO-AC3/11_CAMS"
ecrad = "E:/HALO-AC3/08_ecrad"
libradtran_exp = "E:/HALO-AC3/12_libRadtran"  # folder for libRadtran experiments
ozone = "E:/HALO-AC3_raw_only/05_ozone_sondes"  # ozone sondes from Ny-Alesund
trajectories = "E:/HALO-AC3/07_trajs"  # trajectories from LAGRANTO using ERA5 data
era5 = "E:/HALO-AC3/10_ERA5"  # ERA5 data as downloaded by Benjamin

[halo-ac3.jr_ubuntu]
base_dir = "/mnt/e/HALO-AC3/02_Flights"
raw = "SMART/raw"  # raw measurements as given by SMART
data = "SMART/data_cor"  # dark current corrected data
calibrated = "SMART/data_calibrated"  # calibrated and dark current corrected data
quicklooks = "quicklooks"  # quicklook path
horidata = "horidata"  # INS and stabilization data
bahamas = "BAHAMAS"  # BAHAMAS measurement files
bacardi = "BACARDI"  # BACARDI measurement files
libradtran = "libRadtran"  # LibRadTran simulation files
satellite = "satellite"  # satellite images
dropsondes = "dropsondes/Level_1"  # dropsonde quality controlled nc files
kt19 = "KT19"
hamp_mira = "hamp_mira"  # radar data from mira
wales = "WALES"  # lidar data from WALES
varcloud = "varcloud_retrieval"  # varcloud retrieval from LMU using WALES and HAMP
all = "all"  # all measurements from one instrument in on instrument folder
plot = "/mnt/c/Users/Johannes/Documents/campaigns/HALO-AC3/case_studies"  # standard plot path
calib = "/mnt/e/HALO-AC3/03_Calibration"  # calibration measurements
pixel_wl = "/mnt/c/Users/Johannes/Documents/Doktor/instruments/SMART/pixel_wl"  # pixel to wavelength mapping files
lamp = "/mnt/c/Users/Johannes/Documents/Doktor/instruments/SMART/lamp_F1587"  # lamp specification files
cosine = "/mnt/c/Users/Johannes/Documents/Doktor/instruments/SMART/cosine_correction_factors"  # cosine correction factors
gopro = "/mnt/e/HALO-AC3/04_Gopro"  # directory of GoPro time lapse pictures
ifs_raw = "/mnt/e/HALO-AC3_raw_only/09_IFS_ECMWF"  # raw IFS data as downloaded
ifs = "/mnt/e/HALO-AC3/09_IFS_ECMWF"  # IFS data after first processing
cams_raw = "/mnt/e/HALO-AC3_raw_only/11_CAMS"
cams = "/mnt/e/HALO-AC3/11_CAMS"
ecrad = "/mnt/e/HALO-AC3/08_ecrad"
libradtran_exp = "/mnt/e/data/HALO-AC3/12_libRadtran"  # folder for libRadtran experiments
ozone = "/mnt/e/HALO-AC3_raw_only/05_ozone_sondes"  # ozone sondes from Ny-Alesund
trajectories = "mnt/e/HALO-AC3/07_trajs"  # trajectories from LAGRANTO using ERA5 data
era5 = "mnt/e/HALO-AC3/10_ERA5"  # ERA5 data as downloaded by Benjamin

# on LIM server
[halo-ac3.lim_server]
base_dir = "/projekt_agmwend/data/HALO-AC3/02_Flights"
raw = "SMART/raw"  # raw measurements as given by SMART
data = "SMART/data_cor"  # dark current corrected data
calibrated = "SMART/data_calibrated"  # calibrated and dark current corrected data
quicklooks = "quicklooks"
horidata = "horidata"  # path to INS and stabilization data
bahamas = "BAHAMAS"  # path to BAHAMAS measurement files
bacardi = "BACARDI"  # BACARDI measurement files
libradtran = "libRadtran"  # LibRadtran simulation files
satellite = "satellite"  # satellite images
dropsondes = "dropsondes/Level_1"  # dropsonde quality controlled nc files
kt19 = "KT19"
hamp_mira = "hamp_mira"  # radar data from mira
wales = "WALES"  # lidar data from WALES
varcloud = "varcloud_retrieval"  # varcloud retrieval from LMU using WALES and HAMP
all = "all"  # all measurements from one instrument in on instrument folder
plot = "/projekt_agmwend/home_rad/jroettenbacher/case_studies"  # general folder for plots
calib = "/projekt_agmwend/data/HALO-AC3/03_Calibration"  # calibration measurements
pixel_wl = "/projekt_agmwend/kalibration/Spektros/pixel_wl"  # pixel to wavelength mapping files
lamp = "/projekt_agmwend/kalibration/Lamps/FEL-1587"  # lamp specification files
cosine = "/projekt_agmwend/kalibration/Cosinuskorrekturfaktoren/HALO_Einlässe"  # cosine correction factors
gopro = "/projekt_agmwend/data/HALO-AC3/04_Gopro"  # directory of GoPro timestamps files
ifs_raw = "/projekt_agmwend2/data_raw/HALO-AC3_raw_only/09_IFS_ECMWF"  # raw IFS data as downloaded
ifs = "/projekt_agmwend/data/HALO-AC3/09_IFS_ECMWF"  # IFS data after first processing
cams_raw = "/projekt_agmwend2/data_raw/HALO-AC3_raw_only/11_CAMS"
cams = "/projekt_agmwend/data/HALO-AC3/11_CAMS"
ecrad = "/projekt_agmwend/data/HALO-AC3/08_ecrad"
libradtran_exp = "/projekt_agmwend/data/HALO-AC3/12_libRadtran"  # folder for libRadtran experiments
ozone = "/projekt_agmwend2/data_raw/HALO-AC3_raw_only/05_ozone_sondes"  # ozone sondes from Ny-Alesund
trajectories = "/projekt_agmwend/data/HALO-AC3/07_trajs"  # trajectories from LAGRANTO using ERA5 data
era5 = "/projekt_agmwend/home_rad/BenjaminK/HALO-AC3/models/ERA5/ERA5_ml_noOMEGAscale"  # ERA5 data as downloaded by Benjamin