# paths to files
[cirrus-hl]

[cirrus-hl.jr_local]
base_dir = "C:/Users/Johannes/Documents/Doktor"
raw_data = "campaigns/CIRRUS-HL/SMART/raw"  # raw measurements as given by SMART and merged by smart_merge_minutely_files.py
calib_data = "campaigns/CIRRUS-HL/SMART/calib"  # calibration measurements
data = "campaigns/CIRRUS-HL/SMART/data_cor"  # dark current corrected data
calibrated_data = "campaigns/CIRRUS-HL/SMART/data_calibrated"  # calibrated and dark current corrected data
plots = "campaigns/CIRRUS-HL/SMART/plots"
pixel_to_wavelength = "instruments/SMART/pixel_wl"  # pixel to wavelength mapping files
lamp = "instruments/SMART/lamp_F1587"  # lamp specification files
panel = "instruments/SMART/panel_34816"  # panel reflectivity files
horidata = "campaigns/CIRRUS-HL/horidata"  # path to INS and stabilization data
bahamas = "campaigns/CIRRUS-HL/BAHAMAS"
# on LIM server
[cirrus-hl.lim_server]
base_dir = "/projekt_agmwend"
pixel_to_wavelength = "kalibration/Spektros/pixel_wl"
calib_data = "data/Cirrus_HL/SMART"
